### PR TITLE
Use vendored broker-cli library in installer.

### PR DESCRIPTION
**Pull request by bmelville**
@droot I'm not sure if there is a better way to do this that I'm missing, as this essentially vendors itself in order to get the broker-cli stuff.

Makes progress on #75.

### CODE REVIEW

**Comment by bmelville** [comment]
Hey @droot, sorry it's taken a while to circle back to this. I have also now removed the old broker-cli package, so PTAL.

Thanks,
B.

**Comment by droot** [comment]
LGTM. Is it all set to be merged ?

**Comment by bmelville** [comment]
Yessir!

**Comment by droot** [comment]
Awesome! Merged!

**Pull request merged**
